spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/iso_validator_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  cloud:
    config:
      enabled: false

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  private-key-path: E:/ISO_Backend/iso8583-validator-backend/keys/private.pem
  public-key-path: E:/ISO_Backend/iso8583-validator-backend/keys/public.pem
  expiration-ms: 28800000  # 8 hours

logging:
  level:
    com.verinite.auth_service: DEBUG