package com.verinite.common.enums;

public enum AuditAction {
    CREATE, UPDATE, DELETE,
    ACTIVATE, DEACTIVATE,
    LOGIN, LOGOUT, LOGIN_FAILED,
    ACCOUNT_LOCKED, PASSWORD_CHANGE,
    TEST_CONNECTION,
    FORMAT_HOT_RELOAD, FORMAT_VALIDATE_XML,
    RULE_IMPORT, RULE_EXPORT,
    PROMPT_ROLLBACK, FORMAT_ROLLBACK,
    SESSION_REVOKE, SET_DEFAULT,
    ROLE_CHANGE, USER_LOCKED, USER_UNLOCKED
}