spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iso8583_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  expiry-minutes: 60