spring:
  application:
    name: validation-engine
  datasource:
    url: jdbc:mysql://localhost:3306/iso_validator_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=30s
    cache-names:
      - profileFormats
      - rulesCache
  cloud:
    config:
      enabled: false

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.verinite.validation: DEBUG